### ISSUE TITLE
Misnamed Function In Lab Description

### ISSUE THREAD

**Issue by ecssiah** [learn-co-curriculum/js-ajax-fetch-lab#1]
In the description of the lab, they mention using a `showForkedRepo` function to display the repo, but the function provided in the `index.js` file with the lab is called `showResults`. These should probably be matched to avoid confusion.

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @ecssiah.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
