### ISSUE TITLE
Tests Unaware Of JQuery

### ISSUE THREAD

**Issue by ecssiah** [learn-co-curriculum/js-ajax-fetch-lab#2]
The JQuery script is included in the `index.html` file for this lab, but the tests do not seem to be aware of it, so students may be misled into thinking they can use JQuery to solve this lab.

When I used the $ from JQuery I get a reference error when running the tests, but not when running the application in my browser.

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @ecssiah.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
