### ISSUE TITLE
Feels out of tone for Flatiron 

### ISSUE THREAD

**Issue by MiriamPeskowitz** [learn-co-curriculum/js-ajax-fetch-lab#3]
There's a big difference between the tone of the ruby/rails vs js lessons and labs. This one feels like a different school; I've liked the ways that Flatiron has felt non-conventional in terms of gender, and this lab's gifs and writing just made me feel like I'm a tech-bro place, like so many others in tech, instead of Flatiron's usual amazing trick of feeling incredible non-stereotypical. This stuff is just getting in the way of feeling comfortable enough here to learn. It's no fun to have to fight through the curriculum, if you know what I mean. Thanks. These are easy changes to make. 

Pasting some in here: 

Using fetch to get remote data after using XMLHttpRequest is a little like riding in a convertible with the top down after spending your whole life walking like a sucker.

mean girls-- with the shopping comment

**Comment by maxwellbenton** [comment]
Thank you for spotting this, @MiriamPeskowitz.

We have updated the materials in this lesson, removed the animated GIFs and the content you pasted. We appreciate your feedback as it helps us make our content as welcoming and easy to access as possible.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
