### ISSUE TITLE
Incorrect Lab name in index-test.js

### ISSUE THREAD

**Issue by JuanGongora** [learn-co-curriculum/js-ajax-fetch-lab#31]
If we put the correct lab string, we get an error:

`Error: Expected 'https://api.github.com/repos/juangongora/js-ajax-fetch-lab-v-000/issues' to match /js-ajax-fetch-lab\/issues/`

So when the api tries to fetch the associated issues we get a 410 error

Solution:

change `js-ajax-fetch-lab` string in `index-test.js` to `js-ajax-fetch-lab-v-000`
Otherwise the tests pass if we keep it the old way, but the actual functionality of the site when used doesn't really work.

**Comment by sgharms** [comment]
Thanks! Fixed in: 4bc4eba
