### ISSUE TITLE
confusing instructions

### ISSUE THREAD

**Issue by d-d-d-dalia** [learn-co-curriculum/js-ajax-fetch-lab#4]
This lab confuses students for a few reasons. Here are a couple things I've noticed:

1) functions that are pre-defined in the master code are named differently than how they are referenced in the instructions. e.g. showForkedRepo vs showResults

2) running learn sometimes doesn't display the test failure details. this may have to do with with node and/or npm versions. students may need to edit node version as in step 15 here http://help.learn.co/workflow-tips/local-environment/mac-osx-manual-environment-set-up, and then run npm test, instead of learn. however, doing that makes running learn in the Ruby labs break. running `rvm -v` (Ruby version manager) tells you what to do to fix it.

**Comment by maxwellbenton** [comment]
Hi @d-d-d-dalia,

Thank you for spotting this issue and providing feedback.

I have updated the instructions, starter code and solution for this lesson. I also added a reference to step 15 in the environment set up.

If there are any students that have already forked this lesson and would like the updated version, they will need to delete their current fork and revisit the lesson on learn.co.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
