### ISSUE TITLE
Error messages do not appear when running `learn`

### ISSUE THREAD

**Issue by ivalentine** [learn-co-curriculum/js-ajax-fetch-lab#43]
When running `learn`, the full error messages do not appear; only the summary appears. Here is the output:

```
> js-ajax-fetch-lab@0.1.0 test /home/bebopvinh/development/labs/js-ajax-fetch-lab-online-web-ft-021119
> mocha -R mocha-multi --reporter-options nyan=-,json=.results.json

 2   -_-_-__,------,
 3   -_-_-__|  /\_/\ 
 0   -_-_-_~|_( x .x) 
     -_-_-_ ""  "" 
npm ERR! Test failed.  See above for more details.
```

I was able to reproduce this in my local environment:
macOS 10.14.2
Node 10.5.3
NPM 6.9.0
N (not NVM) 2.1.12

This was reported by @BebopVinh, who is using this local environment:
Ubuntu 19.04
Node 10.16.0
NPM 6.9.0
NVM 0.34.0

**Comment by kyoung90** [comment]
We got the errors to appear by changing node version from 12.0.1 to 8.9.1  @ivalentine

**Comment by sgharms** [comment]
Yikes! We should definitely not be requiring a down-revision of Node in order for these tests to work.

**Comment by maxwellbenton** [comment]
Hi @ivalentine,

Thank you for spotting this and providing feedback. We've updated the dependencies and tests in this lesson. The tests should now appear for any students forking this lab from now on.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
