### ISSUE TITLE
Test is looking for incorrect url 

### ISSUE THREAD

**Issue by jebediahelliott** [learn-co-curriculum/js-ajax-fetch-lab#5]
In the test for the `forkRepo()` function it has the following: `expect(url).toMatch(
        /api.github.com\/repos\/learn-co-curriculum\/js-ajax-fetch-lab/
      );`
This url is incomplete. In the github docs it specifies `POST /repos/:owner/:repo/forks`. The test should have `/forks` on the end of the url it is expecting.

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @jebediahelliott.

We have updated the test to look for `/api.github.com\/repos\/learn-co-curriculum\/js-ajax-fetch-lab\/forks/` and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
